### ISSUE TITLE
Highlighting dialogue: buttons "Add/Remove selected to/from list"

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#548] opened 2021-06-01 10:57 UTC
As a user, I want to be more flexible with the selection of stations to highlight and I want to use manual selections

Add a buttons: "Add selected to list" and "Remove selected from list"

Position of buttons: on the right side next to "choose color"
Umbrechen des textes in button, zwei buttons nebeneinander; 
wenn bildschirm zu klein, zwei buttons kommen in neue Zeile (unter choose shape/color)

When clicking the buttons, the stations should be converted to a list of station IDs.

This tickets includes the functionality of the buttons. 

**Think of Tests**
- [ ] Excel testsheet needed
- [ ] E2e test needed
- [ ] Integration test needed
- [ ] Unit test needed

**Additional context**
- [ ] Mockup needed

**Comment by ruegenbfr** [comment] 2021-07-01 18:28
##### Solution deviates from specification as follows:
- the button to add the graph selection to the conditions is **labeled** "**Add Selection**" instead of "Add selected to list"
- the button to remove the graph selection from the conditions is **labeled** "**Remove Selection**" instead of "Remove selected from list"
- the add button has the **tooltip** "**Add conditions for graph selection**"
- the remove button has the **tooltip** "**Remove conditions for graph selection**"

##### Please note:
If a lot of stations are selected, the complex filter becomes very slow. This is not caused by the new feature but by the implementation of the complex filter. This issue is addressed in a new ticket.

**Comment by bfrgottscma** [comment] 2021-08-23 11:31
The "Remove" button does not seem to be functional in edit mode when having a highlighting condition, that was created via the "Add Selection" function and when this rule is saved.

**Comment by bfrgottscma** [comment] 2021-08-29 21:27
Buttons functional in edit mode as well. And it is even possible to combine conditions and adding stations via the selection button. GREAT!!!!

Done

Tested with Example Data
Windows 10
Firefox (91.0.1 (64-Bit)) and Chrome (Version 92.0.4515.159 (Offizieller Build) (64-Bit))

**Closed** 2021-08-30 08:48 UTC
Labels: Story
