### ISSUE TITLE
Improve size of roa boxes

### ISSUE THREAD

**Issue by ruegenbfr** [SiLeBAT/fcl-client#770] opened 2024-02-23 09:05 UTC
The roa boxes (e.g. lot boxes) show different horizontal spacing between boundary and label.

The box size is determined by its label content but currently the label size is only estimated based on its character count / line count.
This means the labels '**wwww**' and '**iiii**' have the same estimated width but actually their width is very different.
This can also cause that a box could be to small for a label.

#### Reproduce:
- load Example data
- generate roa report
   --> The top left station box '**Primary producer: Poultry farm Roland**' is next to the station '**Trader: Spices Of The World Ltd.**' . The both show different space between label and (horizontal) boundary.

#### Solution:
Please use the js api to determine the exact dimensions of the labels.

**Comment by ruegenbfr** [comment] 2024-02-28 14:47
Done!
Roa box labels are measured by browser api now.

**Comment by afalenski** [comment] 2024-04-12 08:03
I can reproduce the issue that the station name runs out of the white station ROA box in FCL Web Prod only for zoom 120% (ROA zoom) or 110% (Browser zoom), but not for other zoom steps. In FCL Web Dev it is now fixed, the station box width adapts to long station names:
<img width="1301" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlpXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbfccc07098c8dccea8898cbe47ab54f54f37d96/grafik.png" alt="grafik.png" />

I cannot reproduce the following from the ticket text, neither in FCL Web Prod nor in Dev:
 _The top left station box 'Primary producer: Poultry farm Roland' is next to the station 'Trader: Spices Of The World Ltd.' . The both show different space between label and (horizontal) boundary._

**Closed** 2024-04-19 08:52 UTC
Labels: Story
