### ISSUE TITLE
E2e test for GDPR agreement verification

### ISSUE THREAD

**Issue by bfrgottscma** [SiLeBAT/fcl-client#608] opened 2022-01-31 12:00 UTC
Add a e2e test to check whether User Consent to Data Protection Declaration is processed correctly.

#### Background:
- if the data protection declaration changed date is unset on the server side, the user has to consent each time on login

**Comment by birgitlewicki** [comment] 2022-06-17 12:23
duplicate of #546

**Closed** 2022-07-01 09:18 UTC
Labels: Duplicate, Task
